# Generated by Django 5.0.4 on 2024-05-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_on",
            field=models.DateTimeField(),
        ),
    ]
