# Generated by Django 5.0.4 on 2024-05-02 15:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_alter_listing_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_on",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
