# Generated by Django 5.0.4 on 2024-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_alter_listing_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
